ALTER TABLE sections ADD COLUMN maqam TEXT;
ALTER TABLE sections ADD COLUMN tonic TEXT;
ALTER TABLE sections ADD COLUMN tempo INTEGER;
ALTER TABLE sections ADD COLUMN energy INTEGER;
ALTER TABLE sections ADD COLUMN moves TEXT NOT NULL DEFAULT '';
ALTER TABLE tracks ADD COLUMN genre TEXT NOT NULL DEFAULT '';
